### ISSUE TITLE
Built with outdated libcanberra? Causing crash on wayland

### ISSUE THREAD

**Issue by saivert** [flathub/org.pulseaudio.pavucontrol#11] opened 2020-11-03 20:42 UTC
According to http://git.0pointer.net/libcanberra.git/ it seems this was patched years ago but doesn't look like any new release was made.
So this should build with a newer version or at least a patched version of libcanberra.

**Comment by wjt** [comment] 2020-11-03 20:59
Good catch. Happy to review a PR to either build against that Git commit, or to add that patch against the v0.30 tarball.

**Comment by saivert** [comment] 2020-11-03 21:41
While that would fix the crash, pavucontrol would still not play the sound when you drag the volume slider. The code needs more fixes to work on Wayland. Perhaps switching to GSound would be better. It still uses libcanberra under the hood but has a different implementation of it.

Edit: I submitted a simple PR now so the crashing stops as a first step.

**Comment by wjt** [comment] 2020-11-04 10:03
Thanks, let's close this having merged #12.

Making the slider actually work on Wayland is something which needs to be addressed upstream. I found https://gitlab.freedesktop.org/pulseaudio/pavucontrol/-/issues/68 tracking this.

**Closed as completed by wjt** 2020-11-04 10:03 UTC

**Comment by tanuk** [comment] 2020-11-04 17:35
@wjt, what needs to be addressed upstream? The pavucontrol issue 68 seems to be only about the crash caused by an old libcanberra version.

**Comment by wjt** [comment] 2020-11-04 17:39
On Wayland, with this patch, moving a slider still spews g_warning()s to the journal. Looking at the patch it just makes all these functions early-return somewhat gracefully rather than crashing outright.
